### PR TITLE
Main spring2023

### PR DESCRIPTION
**Pull request by EzequielHS05**
Merging changes Spring2023

### CODE REVIEW

**Review by DFiggy831 — APPROVED** [review]
Looks good!

**Comment by wadecosta** [comment]
It looks like there are no merge issues, and it looks like the algorithm/API is present. Looks good to me!

**Review by wadecosta — APPROVED** [review]
It looks like there are no merge issues, and it looks like the algorithm/API is present. Looks good to me!

**Review by CyberGavSpie — APPROVED** [review]
No issues with User, Course, or Classroom Management!

**Pull request merged**
